name: WatchState
version: "1.0.2.9.2"
slug: watchstate
description: Self-hosted service to sync Plex, Jellyfin and Emby play state
url: "https://github.com/arabcoders/watchstate"
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web UI
webui: "http://[HOST]:[PORT:8080]"
map:
  - config:rw
watchdog: "tcp://[HOST]:8080"
image: "ghcr.io/stainy3244/addon-watchstate-{arch}"

