name: WatchState
version: "1.0.2"
slug: watchstate
description: Self-hosted service to sync Plex, Jellyfin and Emby play state
url: https://github.com/arabcoders/watchstate
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web UI
webui: "http://[HOST]:[PORT:8080]"
options:
  UID: 1000
  GID: 1000
schema:
  UID: int(0,65535)
  GID: int(0,65535)
map:
  - config:rw
watchdog: "tcp://[HOST]:8080"
image: "ghcr.io/stainy3244/addon-watchstate-{arch}"
